spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5430/userauth
    username: root
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5430/userauth
    user: root
    password: password
    locations: classpath:db/migrations
    enabled: true
  jwt:
    secret: SomeSecretKeySomeSecretKeySomeSecretKeySomeSecretKeySomeSecretKey
    duration: 30m
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 0



