spring:
  application:
    name: user-server
  datasource:
    url: jdbc:postgresql://localhost:5430/userData
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5430/userData
    user: root
    password: password
    locations: classpath:db/migrations
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  default:
    linksPerDay: 10

server:
  port: 0


