spring:
  application:
    name: gateway-point
  jwt:
    secret: SomeSecretKeySomeSecretKeySomeSecretKeySomeSecretKeySomeSecretKey

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  UrlPath: localhost/