spring:
  application:
    name: gateway-point

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#springdoc:
#  api-docs:
#    path: /dock/api-docs
#  swagger-ui:
#    path: /dock/swagger-ui-custom.html