spring:
  application:
    name: gateway-point
  jwt:
    secret: SomeSecretKeySomeSecretKeySomeSecretKeySomeSecretKeySomeSecretKey
  cloud:
    gateway:
        mvc:
          routes:
          - id: accessControl-service
            uri: lb://accessControl-service
            predicates:
              - Path=/users/{id}/roles
              - Method=PATCH
              - Path=/permissions/{userId}
              - Method=GET
          - id: authenticate-service
            uri: lb://authenticate-service
            predicates:
              - Path=/sing-in,/log-in
              - Method=POST
          - id: url-service
            uri: lb://url-service
            predicates:
              - Path=/urls/**
              - Method=GET,DELETE
              - Path=/sh/**
              - Method=GET
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/user
              - Method=GET
              - Path=/users/**
              - Method=GET,POST

server:
  port: 8080
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

app:
  UrlPath: localhost:8080/
  publicApi:
    - "/sing-in"
    - "/log-in"
    - "/sh/**"