spring:
  application:
    name: url-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    routs:
      expiredLinkRout: notification.linkExpired
      createInfoRoutKey: notification.linkCreated
    exchangers:
      notificationExchange: notification
  datasource:
    url: jdbc:postgresql://localhost:5430/url
    username: root
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5430/url
    user: root
    password: password
    locations: classpath:db/migrations
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  default:
    defaultLinkPath: localhost/
  delays:
    linkDuration: 10d
    cronDelay: 50 23 * * * *
    linkCheckDelay: 10d


server:
  port: 0



