spring:
  application:
    name: url-service
  datasource:
    url: jdbc:postgresql://localhost:5430/url
    username: root
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5430/url
    user: root
    password: password
    locations: classpath:db/migrations
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  default:
    linkDurationDays: 10
    defaultLinkPath: localhost/

server:
  port: 0



